---
- hosts: all
  user: ubuntu
  sudo: yes    
  roles:
    - { role: rvm_io.ruby,
        tags: ruby,
        rvm1_rubies: ['ruby-2.3.1'],
        rvm1_user: 'ubuntu',
        become: true
      }
      
  tasks:       


#Por alguna razon instala todos los paquetes menos libpq-dev

  -  name: Instalamos  paquetes necesarios
     become: true
     action: >
      {{ ansible_pkg_mgr }} name= {{ item }}  state=installed update_cache=yes
     with_items:
      - build-essential
      - ruby-dev
      - libpq-dev
      - ruby
      - git
      - libgdbm-dev
      - libncurses5-dev
      - automake
      - libtool
      - bison
      - libffi-dev
      
  -  name: clonamos repo de la web
     become: true  
     become_user: ubuntu
     shell: git clone  https://github.com/LuisGi93/pradobot.git
     args:
       creates: pradobot
       executable: /bin/bash

  -  name: Instalamos el proyecto
     become: true  
     become_user: ubuntu 
     shell: source ~/.rvm/scripts/rvm && bundle install 
     args:
       chdir: pradobot
       executable: /bin/bash
         
  
  -  name: Lo arrancamos
     become: true  
     become_user: ubuntu
     shell:source ~/.rvm/scripts/rvm && export TOKEN_BOT_MOODLE='' && export MOODLE_HOST="127.0.0.1/moodle" && export TOKEN_BOT='' && export URL_DATABASE=""  && ruby bin/run.rb start
     args:
       chdir: pradobot
       executable: /bin/bash

